[{"name": "test.test_to_grayscale.ToGrayscale.test_blue", "status": "failed", "message": "src.to_grayscale.to_blue does not exist!", "passed": false, "points": ["p03-11.2"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/test/test_to_grayscale.py\", line 56, in test_blue\n    b = to_blue(self.a)\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_to_grayscale.ToGrayscale.test_gray", "status": "errored", "message": "Object does not appear to be a 8-bit string path or a Python file-like object", "passed": false, "points": ["p03-11.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/test/test_to_grayscale.py\", line 31, in test_gray\n    g = to_grayscale(self.a)\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/src/to_grayscale.py\", line 7, in to_grayscale\n    picha = plt.imread(imej)\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/matplotlib/pyplot.py\", line 2135, in imread\n    return matplotlib.image.imread(fname, format)\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/matplotlib/image.py\", line 1436, in imread\n    return handler(fname)\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/matplotlib/image.py\", line 1390, in read_png\n    return _png.read_png(*args, **kwargs)\n"]}, {"name": "test.test_to_grayscale.ToGrayscale.test_green", "status": "failed", "message": "src.to_grayscale.to_green does not exist!", "passed": false, "points": ["p03-11.2"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/test/test_to_grayscale.py\", line 49, in test_green\n    g = to_green(self.a)\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_to_grayscale.ToGrayscale.test_main", "status": "failed", "message": "Expected 'show' to have been called.", "passed": false, "points": ["p03-11.2"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/test/test_to_grayscale.py\", line 68, in test_main\n    pshow.assert_called()\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/mock.py\", line 845, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_to_grayscale.ToGrayscale.test_red", "status": "failed", "message": "src.to_grayscale.to_red does not exist!", "passed": false, "points": ["p03-11.2"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/test/test_to_grayscale.py\", line 42, in test_red\n    r = to_red(self.a)\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e11_to_grayscale/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}]