[{"name": "test.test_powers_of_series.PowersOfSeries.test_called", "status": "passed", "message": "", "passed": true, "points": ["p04-02.1"], "backtrace": []}, {"name": "test.test_powers_of_series.PowersOfSeries.test_content", "status": "failed", "message": "\nArrays are not equal\nIncorrect values in column 1 for Series\na    1\nb    1\nc    4\nd    0\ndtype: int64!\nMismatched elements: 1 / 4 (25%)\nMax absolute difference: 60\nMax relative difference: 15.\n x: array([ 1,  1, 64,  0])\n y: array([1, 1, 4, 0])", "passed": false, "points": ["p04-02.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part04-e02_powers_of_series/test/test_powers_of_series.py\", line 46, in test_content\n    np.testing.assert_array_equal(df[i], s**i, err_msg=\"Incorrect values in column %i for Series\\n%s!\" % ( i, s))\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 936, in assert_array_equal\n    verbose=verbose, header='Arrays are not equal')\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 846, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_powers_of_series.PowersOfSeries.test_dimensions", "status": "passed", "message": "", "passed": true, "points": ["p04-02.1"], "backtrace": []}, {"name": "test.test_powers_of_series.PowersOfSeries.test_type", "status": "passed", "message": "", "passed": true, "points": ["p04-02.1"], "backtrace": []}]