[{"name": "test.test_regression.Regression.test_00_imports", "status": "failed", "message": "False is not true : Module statsmodels was not loaded!", "passed": false, "points": ["p08-01.0"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 73, in test_00_imports\n    self.assertTrue(\"statsmodels\" in locals(), msg=\"Module statsmodels was not loaded!\")\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 705, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_01_load", "status": "failed", "message": "Expected 'read_csv' to have been called.", "passed": false, "points": ["p08-01.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 83, in test_01_load\n    prc.assert_called()\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/mock.py\", line 845, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_02_rescale", "status": "failed", "message": "False is not true : Could not find function 'rescale'!", "passed": false, "points": ["p08-01.2"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 97, in test_02_rescale\n    self.assertTrue(\"rescale\" in locals(), msg=\"Could not find function 'rescale'!\")\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 705, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_03_rescaled_variables", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.3"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 113, in test_03_rescaled_variables\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_04_sbp1", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.4"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 130, in test_04_sbp1\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_05_sbp_with_age", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.5"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 146, in test_05_sbp_with_age\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_06_sbp_with_interactions", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.6"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 159, in test_06_sbp_with_interactions\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_07_sbp_with_interactions_visualization", "status": "errored", "message": "module 'statsmodels' has no attribute 'graphics'", "passed": false, "points": ["p08-01.7"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 175, in test_07_sbp_with_interactions_visualization\n    wraps=statsmodels.graphics.regressionplots.abline_plot) as abplot:\n"]}, {"name": "test.test_regression.Regression.test_08_sbp_with_cigarets", "status": "errored", "message": "module 'statsmodels' has no attribute 'graphics'", "passed": false, "points": ["p08-01.8"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 195, in test_08_sbp_with_cigarets\n    wraps=statsmodels.graphics.regressionplots.abline_plot) as abplot:\n"]}, {"name": "test.test_regression.Regression.test_09_high_blood_pressure", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.9"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 224, in test_09_high_blood_pressure\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_10_high_blood_pressure2", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.10"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 242, in test_10_high_blood_pressure2\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_11_high_blood_pressure3", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.11"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 268, in test_11_high_blood_pressure3\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_12_train_test_split", "status": "failed", "message": "False is not true : Could not find function 'train_test_split' {'self': <test.test_regression.Regression testMethod=test_12_train_test_split>, 'orig':           0         1         2  ...         7         8         9\n0 -0.069288  1.000900  1.060030  ...  0.053965  1.010980 -0.707145\n1 -3.287304 -0.336871 -0.073570  ...  0.699822  1.197488 -0.834479\n2  0.044488  0.268264  0.604689  ... -1.606416  0.952089  0.258438\n3  1.521694 -0.849672  0.781447  ... -0.439210  0.212066  0.219303\n4  1.119110  0.977053 -0.656595  ...  0.726301 -0.220216  0.047966\n5 -1.552686 -1.195758  0.084454  ... -0.226219  0.017639  0.046697\n6  0.916475  1.014556 -0.218364  ... -1.975442  0.243451  1.341573\n7  1.433860  0.103223 -1.050795  ... -1.381813 -0.693199  0.261861\n8  0.198646  0.005109 -0.485948  ...  0.898032 -0.107601  2.126431\n9 -1.103724  1.019232  0.842318  ... -1.391990 -0.812185 -0.123815\n\n[10 rows x 10 columns], 'df':           0         1         2  ...         7         8         9\n0 -0.069288  1.000900  1.060030  ...  0.053965  1.010980 -0.707145\n1 -3.287304 -0.336871 -0.073570  ...  0.699822  1.197488 -0.834479\n2  0.044488  0.268264  0.604689  ... -1.606416  0.952089  0.258438\n3  1.521694 -0.849672  0.781447  ... -0.439210  0.212066  0.219303\n4  1.119110  0.977053 -0.656595  ...  0.726301 -0.220216  0.047966\n5 -1.552686 -1.195758  0.084454  ... -0.226219  0.017639  0.046697\n6  0.916475  1.014556 -0.218364  ... -1.975442  0.243451  1.341573\n7  1.433860  0.103223 -1.050795  ... -1.381813 -0.693199  0.261861\n8  0.198646  0.005109 -0.485948  ...  0.898032 -0.107601  2.126431\n9 -1.103724  1.019232  0.842318  ... -1.391990 -0.812185 -0.123815\n\n[10 rows x 10 columns]}, # exercise 12\n# Put your solution here!!", "passed": false, "points": ["p08-01.12"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 290, in test_12_train_test_split\n    msg=\"Could not find function 'train_test_split' %s, %s!\" % (locals(), exercises[12]))\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 705, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_13_cross_validation", "status": "failed", "message": "'error_model' not found in {'self': <test.test_regression.Regression testMethod=test_13_cross_validation>, 'get_path': <function get_path at 0x7f7e01843b00>} : Could not find variable 'error_model'!", "passed": false, "points": ["p08-01.13"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 315, in test_13_cross_validation\n    self.assertIn(\"error_model\", locals(), msg=\"Could not find variable 'error_model'!\")\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 1119, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 693, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_regression.Regression.test_14_chd", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.14"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 331, in test_14_chd\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_15_chd2", "status": "errored", "message": "'fram'", "passed": false, "points": ["p08-01.15"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 345, in test_15_chd2\n    myfram = locals()[\"fram\"]\n"]}, {"name": "test.test_regression.Regression.test_16_chd_visualization", "status": "failed", "message": "Expected 'scatter' to have been called.", "passed": false, "points": ["p08-01.16"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 368, in test_16_chd_visualization\n    pltscatter.assert_called()\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/mock.py\", line 845, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_17_chd_prediction", "status": "failed", "message": "False is not true : Could not find variable 'point'!", "passed": false, "points": ["p08-01.17"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part08-e01_regression/test/test_regression.py\", line 381, in test_17_chd_prediction\n    self.assertTrue(\"point\" in locals(), msg=\"Could not find variable 'point'!\")\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 705, in assertTrue\n    raise self.failureException(msg)\n"]}]